name: CI Tests and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        pytest --cov=converter --cov-fail-under=100 --cov-report=term-missing

    - name: Check code style with flake8
      run: |
        pip install flake8
        flake8 converter.py test_converter.py --max-line-length=100 --show-source --statistics

